use serde_json::{json, Value};
use std::{
    env, fs,
    path::{Path, PathBuf},
};

use crate::resume::{AgentKind, parse_agent, resume_store_path};

/// Installs the per-agent "save resume" hook so that whenever an agent CLI
/// session ends (or finishes a turn), the last session id + cwd is appended
/// to TonyMux's resume store. The app only ever *reads* the store; nothing
/// here executes agent commands.
///
/// Supported:
/// - Claude Code: command hooks (Stop + SessionEnd) merged into
///   `~/.claude/settings.json`, script at `~/.claude/hooks/`.
/// - Codex: command hook (SessionEnd, timeout 3s max) written to
///   `~/.codex/hooks.json`, script at `~/.codex/hooks/`.
/// - opencode: plugin dropped into the global plugins directory
///   `~/.config/opencode/plugins/` (no hooks config key exists anymore).

const CLAUDE_EVENT: &str = "SessionEnd";
const CLAUDE_STOP_EVENT: &str = "Stop";
const CODEX_EVENT: &str = "SessionEnd";

#[derive(Clone, Debug, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentHooksSetupResult {
    pub agent: AgentKind,
    pub script_path: String,
    pub config_path: String,
    pub message: String,
}

fn home_dir() -> Option<PathBuf> {
    env::var_os("USERPROFILE")
        .map(PathBuf::from)
        .or_else(|| env::var_os("HOME").map(PathBuf::from))
}

/// opencode config root: XDG_CONFIG_HOME or `~/.config` (opencode follows
/// XDG even on Windows native builds).
fn opencode_config_dir() -> Result<PathBuf, String> {
    if let Some(xdg) = env::var_os("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(xdg).join("opencode"));
    }
    let home = home_dir().ok_or_else(|| "neither USERPROFILE nor HOME is available".to_owned())?;
    Ok(home.join(".config").join("opencode"))
}

fn powershell_command(script_path: &Path) -> String {
    format!(
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"{}\"",
        script_path.display()
    )
}

// ---------------------------------------------------------------------------
// Script templates (tokens replaced at write time; no format! brace escaping).
// ---------------------------------------------------------------------------

const POWERSHELL_TEMPLATE: &str = r#"# TonyMux resume saver (__AGENT__) — generated by TonyMux. Do not edit manually.
$ErrorActionPreference = "SilentlyContinue"
try {
  $payload = [Console]::In.ReadToEnd() | ConvertFrom-Json
  if ($null -ne $payload.session_id -and $payload.session_id -ne "") {
    $exe = "__EXECUTABLE__"
    $cmd = Get-Command __EXECUTABLE__ -ErrorAction SilentlyContinue
    if ($null -ne $cmd) { $exe = $cmd.Source }
    $rec = [ordered]@{
      agent = "__AGENT__"
      sessionId = [string]$payload.session_id
      cwd = [string]$payload.cwd
      updatedAt = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
      executable = $exe
      args = @("__RESUME_FLAG__", [string]$payload.session_id, "__CWD_FLAG__", [string]$payload.cwd)
    }
    $json = $rec | ConvertTo-Json -Compress -Depth 4
    Add-Content -LiteralPath "__STORE_PATH__" -Value $json -Encoding utf8
  }
} catch { }
"#;

const OPENCODE_PLUGIN_TEMPLATE: &str = r#"// TonyMux resume plugin — generated by TonyMux. Do not edit manually.
import { appendFileSync, mkdirSync } from "node:fs"
import path from "node:path"

const STORE = "__STORE_PATH__"

export const ResumePlugin = async ({ directory }) => ({
  event: async ({ event }) => {
    if (event.type !== "session.status" && event.type !== "session.idle") return
    if (event.status && event.status.type !== "idle") return
    const sid = event.sessionID
    if (!sid) return
    const rec = {
      agent: "opencode",
      sessionId: sid,
      cwd: directory,
      updatedAt: Date.now(),
      executable: "opencode",
      args: ["--session", sid],
    }
    try {
      mkdirSync(path.dirname(STORE), { recursive: true })
      appendFileSync(STORE, JSON.stringify(rec) + "\n", "utf8")
    } catch (e) {}
  },
})
"#;

fn render_powershell_script(
    agent: AgentKind,
    store_path: &Path,
    resume_flag: &str,
    cwd_flag: &str,
) -> String {
    POWERSHELL_TEMPLATE
        .replace("__AGENT__", agent.as_str())
        .replace("__EXECUTABLE__", agent.as_str())
        .replace("__STORE_PATH__", &store_path.display().to_string())
        .replace("__RESUME_FLAG__", resume_flag)
        .replace("__CWD_FLAG__", cwd_flag)
}

pub fn write_hook_script(
    script_path: &Path,
    agent: AgentKind,
    store_path: &Path,
) -> Result<(), String> {
    if let Some(parent) = script_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("unable to create hook script directory: {error}"))?;
    }
    let (resume_flag, cwd_flag) = match agent {
        AgentKind::Claude => ("--resume", "--cwd"),
        AgentKind::Codex => ("resume", "--cd"),
        AgentKind::Opencode => unreachable!("opencode uses a plugin, not a PowerShell hook"),
    };
    let content = render_powershell_script(agent, store_path, resume_flag, cwd_flag);
    fs::write(script_path, content)
        .map_err(|error| format!("unable to write hook script: {error}"))
}

pub fn write_opencode_plugin(plugin_path: &Path, store_path: &Path) -> Result<(), String> {
    if let Some(parent) = plugin_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("unable to create opencode plugin directory: {error}"))?;
    }
    let content = OPENCODE_PLUGIN_TEMPLATE.replace("__STORE_PATH__", &store_path.display().to_string());
    fs::write(plugin_path, content)
        .map_err(|error| format!("unable to write opencode plugin: {error}"))
}

// ---------------------------------------------------------------------------
// Config merging (serde_json::Value, keeps unrelated keys intact).
// ---------------------------------------------------------------------------

fn load_json(path: &Path) -> Value {
    match fs::read_to_string(path) {
        Ok(text) => serde_json::from_str(&text).unwrap_or(Value::Null),
        Err(_) => Value::Null,
    }
}

fn save_json(path: &Path, value: &Value) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("unable to create config directory: {error}"))?;
    }
    let mut text = serde_json::to_string_pretty(value)
        .map_err(|error| format!("unable to encode config JSON: {error}"))?;
    text.push('\n');
    fs::write(path, text).map_err(|error| format!("unable to write config: {error}"))
}

/// Ensure `root.hooks.<event>` exists and append `entry` unless an entry with
/// the same command already exists (idempotent re-runs).
fn merge_hook_entry(root: &mut Value, event: &str, entry: Value) {
    let hooks = root
        .as_object_mut()
        .map(|object| object.entry("hooks").or_insert_with(|| json!({})))
        .and_then(|hooks| hooks.as_object_mut());
    let Some(hooks) = hooks else {
        return;
    };
    let event_group = hooks
        .entry(event)
        .or_insert_with(|| json!([]))
        .as_array_mut();
    let Some(event_group) = event_group else {
        return;
    };
    let command = entry
        .pointer("/hooks/0/command")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_owned();
    let already_present = event_group.iter().any(|group| {
        group
            .pointer("/hooks/0/command")
            .and_then(Value::as_str)
            .map(|existing| existing == command)
            .unwrap_or(false)
    });
    if !already_present {
        event_group.push(entry);
    }
}

pub fn merge_claude_settings(settings_path: &Path, script_path: &Path) -> Result<(), String> {
    let mut root = load_json(settings_path);
    if !root.is_object() {
        root = json!({});
    }
    let command = powershell_command(script_path);
    merge_hook_entry(
        &mut root,
        CLAUDE_STOP_EVENT,
        json!({ "hooks": [{ "type": "command", "command": command }] }),
    );
    merge_hook_entry(
        &mut root,
        CLAUDE_EVENT,
        json!({ "hooks": [{ "type": "command", "command": command, "timeout": 10 }] }),
    );
    save_json(settings_path, &root)
}

pub fn merge_codex_hooks(hooks_path: &Path, script_path: &Path) -> Result<(), String> {
    let mut root = load_json(hooks_path);
    if !root.is_object() {
        root = json!({});
    }
    let command = powershell_command(script_path);
    merge_hook_entry(
        &mut root,
        CODEX_EVENT,
        json!({ "hooks": [{ "type": "command", "command": command, "timeout": 3 }] }),
    );
    save_json(hooks_path, &root)
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

#[tauri::command]
pub(crate) fn setup_agent_hooks(agent: String) -> Result<AgentHooksSetupResult, String> {
    setup_agent_hooks_impl(parse_agent(&agent)?)
}

pub fn setup_agent_hooks_impl(agent: AgentKind) -> Result<AgentHooksSetupResult, String> {
    let store_path = resume_store_path()?;
    match agent {
        AgentKind::Claude => {
            let home = home_dir().ok_or_else(|| "neither USERPROFILE nor HOME is available".to_owned())?;
            let script_path = home.join(".claude").join("hooks").join("tonymux-save-resume.ps1");
            let settings_path = home.join(".claude").join("settings.json");
            write_hook_script(&script_path, agent, &store_path)?;
            merge_claude_settings(&settings_path, &script_path)?;
            Ok(AgentHooksSetupResult {
                agent,
                script_path: script_path.display().to_string(),
                config_path: settings_path.display().to_string(),
                message: "Claude Code hooks installed: Stop + SessionEnd save the resume command on every turn and at session end.".to_owned(),
            })
        }
        AgentKind::Codex => {
            let home = home_dir().ok_or_else(|| "neither USERPROFILE nor HOME is available".to_owned())?;
            let script_path = home.join(".codex").join("hooks").join("tonymux-save-resume.ps1");
            let hooks_path = home.join(".codex").join("hooks.json");
            write_hook_script(&script_path, agent, &store_path)?;
            merge_codex_hooks(&hooks_path, &script_path)?;
            Ok(AgentHooksSetupResult {
                agent,
                script_path: script_path.display().to_string(),
                config_path: hooks_path.display().to_string(),
                message: "Codex hooks installed: SessionEnd writes the resume command within the 3s teardown budget.".to_owned(),
            })
        }
        AgentKind::Opencode => {
            let config_dir = opencode_config_dir()?;
            let plugin_path = config_dir.join("plugins").join("tonymux-resume.js");
            write_opencode_plugin(&plugin_path, &store_path)?;
            Ok(AgentHooksSetupResult {
                agent,
                script_path: plugin_path.display().to_string(),
                config_path: config_dir.display().to_string(),
                message: "opencode plugin installed in the global plugins directory; session.idle events write the resume command.".to_owned(),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn powershell_script_embeds_store_path_and_flags() {
        let store = PathBuf::from("C:\\Users\\me\\AppData\\Local\\tonymux\\resume\\resume.jsonl");
        let script = render_powershell_script(AgentKind::Claude, &store, "--resume", "--cwd");
        assert!(script.contains("agent = \"claude\""));
        assert!(script.contains("C:\\Users\\me\\AppData\\Local\\tonymux\\resume\\resume.jsonl"));
        assert!(script.contains("\"--resume\", [string]$payload.session_id, \"--cwd\""));
    }

    #[test]
    fn codex_script_uses_resume_and_cd_flags() {
        let store = PathBuf::from("/tmp/resume.jsonl");
        let script = render_powershell_script(AgentKind::Codex, &store, "resume", "--cd");
        assert!(script.contains("args = @(\"resume\", [string]$payload.session_id, \"--cd\""));
    }

    #[test]
    fn merge_preserves_existing_keys_and_events() {
        let mut root = json!({
            "permissions": { "allow": ["Bash(npm run build)"] },
            "hooks": { "PreToolUse": [{ "hooks": [{ "type": "command", "command": "echo hi" }] }] }
        });
        merge_hook_entry(
            &mut root,
            "SessionEnd",
            json!({ "hooks": [{ "type": "command", "command": "powershell.exe -File x.ps1", "timeout": 10 }] }),
        );
        assert_eq!(root["permissions"]["allow"][0], "Bash(npm run build)");
        assert_eq!(root["hooks"]["PreToolUse"].as_array().unwrap().len(), 1);
        assert_eq!(root["hooks"]["SessionEnd"].as_array().unwrap().len(), 1);
        assert_eq!(root["hooks"]["SessionEnd"][0]["hooks"][0]["timeout"], 10);
    }

    #[test]
    fn merge_is_idempotent() {
        let mut root = json!({});
        let entry = json!({ "hooks": [{ "type": "command", "command": "powershell.exe -File x.ps1", "timeout": 10 }] });
        merge_hook_entry(&mut root, "SessionEnd", entry.clone());
        merge_hook_entry(&mut root, "SessionEnd", entry.clone());
        assert_eq!(root["hooks"]["SessionEnd"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn merge_creates_hooks_object_when_missing() {
        let mut root = json!({ "model": "claude-sonnet-4" });
        merge_hook_entry(
            &mut root,
            "Stop",
            json!({ "hooks": [{ "type": "command", "command": "powershell.exe -File y.ps1" }] }),
        );
        assert!(root["hooks"]["Stop"].is_array());
        assert_eq!(root["model"], "claude-sonnet-4");
    }

    #[test]
    fn opencode_plugin_embeds_store_path() {
        let store = PathBuf::from("C:\\Users\\me\\AppData\\Local\\tonymux\\resume\\resume.jsonl");
        let plugin = OPENCODE_PLUGIN_TEMPLATE.replace("__STORE_PATH__", &store.display().to_string());
        assert!(plugin.contains("C:\\Users\\me\\AppData\\Local\\tonymux\\resume\\resume.jsonl"));
        assert!(plugin.contains("session.status"));
        assert!(plugin.contains("\"opencode\""));
    }

    #[test]
    fn script_write_round_trip() {
        let dir = env::temp_dir().join(format!("agent-hooks-test-{}", std::process::id()));
        let script = dir.join("hooks").join("tonymux-save-resume.ps1");
        write_hook_script(&script, AgentKind::Claude, &dir.join("resume.jsonl")).unwrap();
        let content = fs::read_to_string(&script).unwrap();
        assert!(content.contains("# TonyMux resume saver (claude)"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn setup_claude_writes_script_and_merges_settings() {
        let dir = env::temp_dir().join(format!("agent-hooks-setup-{}", std::process::id()));
        let script = dir.join("hooks").join("tonymux-save-resume.ps1");
        let settings = dir.join("settings.json");
        write_hook_script(&script, AgentKind::Claude, &dir.join("resume.jsonl")).unwrap();
        fs::write(&settings, r#"{ "permissions": { "allow": ["Bash(npm test)"] } }"#).unwrap();
        merge_claude_settings(&settings, &script).unwrap();
        let root: Value = serde_json::from_str(&fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(root["permissions"]["allow"][0], "Bash(npm test)");
        assert_eq!(root["hooks"]["Stop"].as_array().unwrap().len(), 1);
        assert_eq!(root["hooks"]["SessionEnd"].as_array().unwrap().len(), 1);
        assert_eq!(root["hooks"]["SessionEnd"][0]["hooks"][0]["timeout"], 10);
        let _ = fs::remove_dir_all(&dir);
    }
}
